// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    {
      type: 'category',
      label: 'Documentation',
      link: { id: 'introduction', type: 'doc' },
      items: [{ type: 'autogenerated', dirName: '.' }],
    },
  ],
};

module.exports = sidebars;
